# Generated by Django 3.2.8 on 2021-12-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejob_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='gender',
        ),
    ]
