# Generated by Django 3.2.8 on 2021-12-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejob_app', '0002_remove_recruiterprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='no_indexing', max_length=1000),
        ),
    ]
