# Generated by Django 3.2.8 on 2021-12-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejob_app', '0004_alter_job_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('S', 'SELECTED'), ('R', 'REJECTED'), ('V', 'APPROVED'), {'I', 'Interview'}], default='M', max_length=10),
        ),
    ]
